import type { CAC } from "cac";
// Embedded domain schemas. These are GENERATED by `bun run gen:schema`
// (scripts/gen-schema.ts), which parses the REAL code sources at generation time:
//   homepage → ClubHome/widgets/index.ts (WIDGET_REGISTRY, 69 kinds) +
//              ai-service/app/prompts/homepage_system.py + club_home_section.py
//   menu     → MenuPreview.tsx (MenuDesignOptions) + supply-service core.py (UnitType)
//   event/task/booking/member → the respective service enum classes.
// Do NOT hand-edit src/schema/*.json — change the source, then run gen:schema.
// `gen:schema:check` fails CI on drift. Embedding the JSON keeps `schema` offline
// + deterministic (no API call, no token). resolveJsonModule + bun --compile
// bundle these into the binary.
import homepage from "../schema/homepage.json" with { type: "json" };
import design from "../schema/design.json" with { type: "json" };
import menu from "../schema/menu.json" with { type: "json" };
import event from "../schema/event.json" with { type: "json" };
import member from "../schema/member.json" with { type: "json" };
import booking from "../schema/booking.json" with { type: "json" };
import task from "../schema/task.json" with { type: "json" };
import sponsor from "../schema/sponsor.json" with { type: "json" };

const SCHEMAS: Record<string, unknown> = { homepage, design, menu, event, member, booking, task, sponsor };

const DOMAIN_SUMMARY: Record<string, string> = {
  homepage: "Tab/Section/Widget-Struktur, 68 Widget-Kinds, config-Felder, Templates",
  design: "Flex-Template Design-Config (hero/sections/decor/type/density) fuer custom_template_config",
  menu: "MenuDesignOptions (design_config) + UnitType + MenuItem-Felder",
  event: "event_type, visibility_scope, organizer_type, status + Create-Felder",
  member: "MemberCreate-Felder + TeamMemberRole",
  booking: "reservation_status, object_type + PATCH-Pflichtfelder",
  task: "status, priority, context_type + Create/Assignment-Felder",
  sponsor: "Lokale Sponsoren, Sponsoring-Angebote, Assignments, Logos und Vertragsdateien",
};

/**
 * `comvenio schema [domain]` — emit the embedded domain schema for the operating
 * agent. `--json` is the DEFAULT (machine-readable is the whole point); pass
 * --pretty for a human-readable domain list. Unknown domain → exit code != 0 +
 * the valid domains on stderr (Sub-File 10 TC-05). No API call, no token.
 */
export function registerSchemaCommand(cli: CAC): void {
  cli
    .command("schema [domain]", "Gueltige Felder/Enums/Widget-Typen einer Domaene (maschinenlesbar)")
    .option("--json", "JSON-Ausgabe (Default an fuer schema)")
    .option("--pretty", "Menschenlesbare Domaenen-Liste (statt JSON)")
    .action((domain: string | undefined, opts: { json?: boolean; pretty?: boolean }) => {
      if (!domain) {
        // No domain → list all domains + summary.
        if (opts.json && !opts.pretty) {
          console.log(
            JSON.stringify(
              {
                domains: Object.keys(SCHEMAS),
                summary: DOMAIN_SUMMARY,
                usage: "comvenio schema <domain> --json",
              },
              null,
              2,
            ),
          );
          return;
        }
        const lines = ["Verfuegbare Schema-Domaenen:", ""];
        for (const d of Object.keys(SCHEMAS)) {
          lines.push(`  ${d.padEnd(10)} ${DOMAIN_SUMMARY[d] ?? ""}`);
        }
        lines.push("", "Nutzung: comvenio schema <domain> --json");
        console.log(lines.join("\n"));
        return;
      }

      const schema = SCHEMAS[domain];
      if (!schema) {
        // Unknown domain → non-zero exit + valid list on stderr (TC-05).
        throw new Error(
          `Unbekannte Domaene "${domain}". Gueltige Domaenen: ${Object.keys(SCHEMAS).join(", ")}.`,
        );
      }
      // Default (and with --json): emit raw JSON. --pretty without --json: also JSON
      // (schema is structured data — human form is just indented JSON).
      console.log(JSON.stringify(schema, null, 2));
    });
}

