import type { ComvenioApiClient, ComvenioHttpMethod } from "@comvenio/comvenio-client";
import { createConnectorError, type JsonValue, type RequestContext } from "@comvenio/connector-contracts";
import { boundedSponsorList, minimizeAssignment, minimizeContract, minimizeDocument, minimizeProduct, minimizeResponsible, minimizeSponsor } from "./privacy.ts";
import type { K13ActionId } from "./types.ts";

type JsonObject = { [key: string]: JsonValue };
type Handler = (input: JsonObject, context: RequestContext, client: ComvenioApiClient) => Promise<JsonValue>;
function record(value: JsonValue): JsonObject { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error("Die validierte K13-Eingabe ist kein Objekt."); return value; }
function string(input: JsonObject, key: string): string { const value = input[key]; if (typeof value !== "string") throw new Error(`${key} fehlt.`); return value; }
function object(input: JsonObject, key: string): JsonObject { return record(input[key] ?? {}); }
function compact(value: Record<string, JsonValue | undefined>): JsonObject { return Object.fromEntries(Object.entries(value).filter((entry): entry is [string, JsonValue] => entry[1] !== undefined)); }
function query(input: JsonObject, mapping: Readonly<Record<string, string>>): Record<string, string> { const out: Record<string, string> = {}; for (const [source, target] of Object.entries(mapping)) { const value = input[source]; if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") out[target] = String(value); } return out; }
function valuesFor(value: JsonValue, keys: Set<string>): string[] { if (value === null || typeof value !== "object") return []; if (Array.isArray(value)) return value.flatMap((entry) => valuesFor(entry, keys)); return Object.entries(value).flatMap(([key, entry]) => keys.has(key) && typeof entry === "string" ? [entry] : valuesFor(entry, keys)); }
function assertTenant(value: JsonValue, context: RequestContext): JsonValue {
  if (context.club_id && valuesFor(value, new Set(["club_id"])).some((id) => id !== context.club_id)) throw createConnectorError({ code: "TENANT_MISMATCH", message: "Der Marketing-Service lieferte Daten eines anderen Vereins.", request_id: context.request_id, retryable: false });
  if (context.department_id && valuesFor(value, new Set(["club_department_id", "department_id"])).some((id) => id !== context.department_id)) throw createConnectorError({ code: "TENANT_MISMATCH", message: "Der Marketing-Service lieferte Daten einer anderen Abteilung.", request_id: context.request_id, retryable: false });
  return value;
}
async function request(client: ComvenioApiClient, context: RequestContext, method: ComvenioHttpMethod, service: string, path: string, options: { body?: JsonValue; query?: Record<string, string> } = {}): Promise<JsonValue> { return client.request<JsonValue>({ method, service, path, context, ...options }); }
const handlers = new Map<string, Handler>(); const key = (id: K13ActionId, operation: string) => `${id}:${operation}`; const add = (id: K13ActionId, operation: string, handler: Handler) => handlers.set(key(id, operation), handler);
function simple(id: K13ActionId, operation: string, method: ComvenioHttpMethod, service: string, path: (input: JsonObject) => string, options: { body?: (input: JsonObject) => JsonValue; query?: (input: JsonObject) => Record<string, string>; map?: (value: JsonValue, input: JsonObject) => JsonValue; deleted?: string } = {}): void {
  add(id, operation, async (input, context, client) => { const value = await request(client, context, method, service, path(input), { ...(options.body ? { body: options.body(input) } : {}), ...(options.query ? { query: options.query(input) } : {}) }); if (options.deleted) return { deleted: true, id: string(input, options.deleted) }; const safe = assertTenant(value, context); return options.map ? options.map(safe, input) : safe; });
}
const sponsorBody = (input: JsonObject): JsonValue => compact({ company_name: input.company_name!, contact_email: input.contact_email!, contact_person: input.contact_person, contact_phone: input.contact_phone, address: input.address, website_url: input.website_url, organization_type: input.organization_type, club_id: input.club_id!, club_department_id: input.department_id! });
const productBody = (input: JsonObject): JsonValue => compact({ club_id: input.club_id!, club_department_id: input.department_id!, name: input.name!, description: input.description, conditions: input.conditions, default_unit_price_cents: input.default_unit_price_cents, currency: input.currency!, billing_interval: input.billing_interval!, default_duration_months: input.default_duration_months, sort_order: input.sort_order! });
const contractBody = (input: JsonObject): JsonValue => compact({ label: input.label, conditions: input.conditions, unit_price_cents: input.unit_price_cents, currency: input.currency!, billing_interval: input.billing_interval!, duration_months: input.duration_months, contract_file_id: input.contract_file_id!, valid_from: input.valid_from!, valid_until: input.valid_until, supersedes_version_id: input.supersedes_version_id, superseded_valid_until: input.superseded_valid_until, note: input.note });

simple("cai.sponsor.01.list", "list", "GET", "marketing", () => "/advertisers/", { query: (input) => query(input, { club_id: "club_id", department_id: "club_department_id" }), map: (value, input) => boundedSponsorList(value, Number(input.limit), minimizeSponsor) });
simple("cai.sponsor.02.show", "show", "GET", "marketing", (input) => `/advertisers/${string(input, "sponsor_id")}`, { map: minimizeSponsor });
simple("cai.sponsor.03.add", "add", "POST", "marketing", () => "/advertisers/", { body: sponsorBody, map: minimizeSponsor });
for (const operation of ["update", "move_department"] as const) add("cai.sponsor.04.update", operation, async (input, context, client) => {
  const path = `/advertisers/${string(input, "sponsor_id")}`; assertTenant(await request(client, context, "GET", "marketing", path), context);
  const body = operation === "update" ? object(input, "changes") : { club_department_id: input.target_department_id! };
  return minimizeSponsor(assertTenant(await request(client, context, "PATCH", "marketing", path, { body }), context));
});
add("cai.sponsor.05.delete", "delete", async (input, context, client) => { const path = `/advertisers/${string(input, "sponsor_id")}`; assertTenant(await request(client, context, "GET", "marketing", path), context); await request(client, context, "DELETE", "marketing", path); return { deleted: true, sponsor_id: input.sponsor_id! }; });
add("cai.sponsor.06.logo", "set", async (input, context, client) => { const path = `/advertisers/${string(input, "sponsor_id")}`; assertTenant(await request(client, context, "GET", "content", `/files/${string(input, "logo_file_id")}`), context); assertTenant(await request(client, context, "GET", "marketing", path), context); return minimizeSponsor(assertTenant(await request(client, context, "PATCH", "marketing", path, { body: { logo_file_id: input.logo_file_id! } }), context)); });

simple("cai.sponsor.07.product_list", "list", "GET", "marketing", () => "/club-sponsorship-products/", { query: (input) => ({ club_id: string(input, "club_id"), ...(typeof input.department_id === "string" ? { club_department_id: input.department_id } : {}), active_only: String(input.include_inactive !== true) }), map: (value, input) => boundedSponsorList(value, Number(input.limit), minimizeProduct) });
simple("cai.sponsor.08.product_add", "add", "POST", "marketing", () => "/club-sponsorship-products/", { body: productBody, map: minimizeProduct });
for (const operation of ["update", "move_department"] as const) simple("cai.sponsor.09.product_update", operation, "PATCH", "marketing", (input) => `/club-sponsorship-products/${string(input, "product_id")}`, { body: (input) => operation === "update" ? object(input, "changes") : { club_department_id: input.target_department_id! }, map: minimizeProduct });
simple("cai.sponsor.10.product_delete", "delete", "DELETE", "marketing", (input) => `/club-sponsorship-products/${string(input, "product_id")}`, { deleted: "product_id" });
simple("cai.sponsor.11.contract_list", "list", "GET", "marketing", (input) => `/club-sponsorship-products/${string(input, "product_id")}/contract-versions`, { map: (value, input) => boundedSponsorList(value, Number(input.limit), minimizeContract) });
add("cai.sponsor.12.contract_add", "add", async (input, context, client) => { assertTenant(await request(client, context, "GET", "content", `/files/${string(input, "contract_file_id")}`), context); const value = await request(client, context, "POST", "marketing", `/club-sponsorship-products/${string(input, "product_id")}/contract-versions`, { body: contractBody(input) }); return minimizeContract(assertTenant(value, context)); });
simple("cai.sponsor.13.contract_update", "update", "PATCH", "marketing", (input) => `/club-sponsorship-products/${string(input, "product_id")}/contract-versions/${string(input, "contract_version_id")}`, { body: (input) => object(input, "changes"), map: minimizeContract });
add("cai.sponsor.13.contract_update", "replace_file", async (input, context, client) => { assertTenant(await request(client, context, "GET", "content", `/files/${string(input, "contract_file_id")}`), context); const value = await request(client, context, "PATCH", "marketing", `/club-sponsorship-products/${string(input, "product_id")}/contract-versions/${string(input, "contract_version_id")}`, { body: { contract_file_id: input.contract_file_id! } }); return minimizeContract(assertTenant(value, context)); });
simple("cai.sponsor.14.contract_delete", "delete", "DELETE", "marketing", (input) => `/club-sponsorship-products/${string(input, "product_id")}/contract-versions/${string(input, "contract_version_id")}`, { deleted: "contract_version_id" });

simple("cai.sponsor.15.assignment_list", "list", "GET", "marketing", () => "/sponsorship-assignments/", { query: (input) => ({ club_id: string(input, "club_id"), ...query(input, { department_id: "club_department_id", sponsor_id: "advertiser_id", status: "status", include_deleted: "include_deleted" }) }), map: (value, input) => boundedSponsorList(value, Number(input.limit), minimizeAssignment) });
simple("cai.sponsor.16.assign", "assign", "POST", "marketing", () => "/sponsorship-assignments/", { body: (input) => compact({ club_id: input.club_id!, club_department_id: input.department_id!, advertiser_id: input.sponsor_id!, sponsorship_product_id: input.product_id!, quantity: input.quantity!, unit_price_cents: input.unit_price_cents, total_price_cents: input.total_price_cents, currency: input.currency!, starts_at: input.starts_at, ends_at: input.ends_at, note: input.note }), map: minimizeAssignment });
simple("cai.sponsor.17.assignment_update", "update", "PATCH", "marketing", (input) => `/sponsorship-assignments/${string(input, "assignment_id")}`, { body: (input) => object(input, "changes"), map: minimizeAssignment });
simple("cai.sponsor.18.cancel", "cancel", "POST", "marketing", (input) => `/sponsorship-assignments/${string(input, "assignment_id")}/cancel`, { body: (input) => compact({ cancellation_note: input.cancellation_note, ends_at: input.ends_at }), map: minimizeAssignment });
simple("cai.sponsor.19.doc_list", "list", "GET", "content", (input) => `/files/by-context/${string(input, "club_id")}/sponsorship_assignment/${string(input, "assignment_id")}`, { map: (value, input) => boundedSponsorList(value, Number(input.limit), minimizeDocument) });

simple("cai.sponsor.21.responsible_list", "list", "GET", "marketing", () => "/sponsor-member-assignments/", { query: (input) => ({ club_id: string(input, "club_id"), ...query(input, { department_id: "club_department_id", sponsor_id: "advertiser_id", member_id: "member_id" }) }), map: (value, input) => boundedSponsorList(value, Number(input.limit), minimizeResponsible) });
simple("cai.sponsor.22.responsible_add", "add", "POST", "marketing", () => "/sponsor-member-assignments/", { body: (input) => compact({ club_id: input.club_id!, club_department_id: input.department_id!, advertiser_id: input.sponsor_id!, member_id: input.member_id!, role: input.role!, is_primary: input.is_primary!, note: input.note }), map: minimizeResponsible });
simple("cai.sponsor.23.responsible_update", "update", "PATCH", "marketing", (input) => `/sponsor-member-assignments/${string(input, "responsible_id")}`, { body: (input) => object(input, "changes"), map: minimizeResponsible });
simple("cai.sponsor.24.responsible_remove", "remove", "DELETE", "marketing", (input) => `/sponsor-member-assignments/${string(input, "responsible_id")}`, { deleted: "responsible_id" });

export function hasK13OperationHandler(actionId: K13ActionId, operation: string): boolean { return handlers.has(key(actionId, operation)); }
export async function executeK13Operation(actionId: K13ActionId, operation: string, input: JsonValue, context: RequestContext, client: ComvenioApiClient): Promise<JsonValue> { const handler = handlers.get(key(actionId, operation)); if (!handler) throw new Error(`${actionId}:${operation}: Der typisierte Handler fehlt.`); return handler(record(input), context, client); }
