import { ToolVisibilityPolicy, type CapabilitySnapshot, type ProviderToolUpdateMode } from "@comvenio/auth";
import { createConnectorError, isConnectorError, normalizeRequestContext, type JsonValue, type RequestContext } from "@comvenio/connector-contracts";
import { z } from "zod";
import { PUBLIC_READ_CONTRACTS } from "../../public/contracts.ts";
import { K13_ACTION_DEFINITIONS, validateK13Definitions } from "./definitions.ts";
import { executeK13Operation, hasK13OperationHandler } from "./handlers.ts";
import { SponsorConfirmationPolicy } from "./policies.ts";
import { buildK13Preview } from "./preview.ts";
import { SponsorVisibilityPolicy } from "./privacy.ts";
import { K13_ACTION_SCHEMAS } from "./schemas.ts";
import type { K13ActionDefinition, K13ActionResult, K13ExecutionDependencies, K13ExecutionRequest, K13MutationRequest, K13OperationDefinition } from "./types.ts";

export interface K13VisibilityRequest { context: RequestContext; capability_snapshot: CapabilitySnapshot | null; provider_tool_updates?: ProviderToolUpdateMode; }
function error(context: RequestContext, code: Parameters<typeof createConnectorError>[0]["code"], message: string): Error { return createConnectorError({ code, message, request_id: context.request_id, retryable: false }); }
function assertJson(value: unknown, context: RequestContext): asserts value is JsonValue { if (!z.json().safeParse(value).success) throw error(context, "VALIDATION_FAILED", "Die Tool-Eingabe enthält ungültige JSON-Werte."); }
function operationFor(definition: K13ActionDefinition, input: JsonValue): K13OperationDefinition { const row = input !== null && typeof input === "object" && !Array.isArray(input) ? input : {}; const names = Object.keys(definition.operations); const name = typeof row.operation === "string" ? row.operation : names.length === 1 ? names[0] : null; const operation = name ? definition.operations[name] : null; if (!operation) throw new Error("Operation fehlt."); return operation; }
function valuesFor(value: JsonValue, keys: Set<string>): string[] { if (value === null || typeof value !== "object") return []; if (Array.isArray(value)) return value.flatMap((entry) => valuesFor(entry, keys)); return Object.entries(value).flatMap(([key, entry]) => keys.has(key) && typeof entry === "string" ? [entry] : valuesFor(entry, keys)); }
function confirmationFrom(input: JsonValue): { preview_id: string; confirmation_token: string } | null { if (input === null || typeof input !== "object" || Array.isArray(input)) return null; const value = input.confirmation; return value !== null && typeof value === "object" && !Array.isArray(value) && typeof value.preview_id === "string" && typeof value.confirmation_token === "string" ? { preview_id: value.preview_id, confirmation_token: value.confirmation_token } : null; }
function withoutConfirmation(input: JsonValue): JsonValue { if (input === null || typeof input !== "object" || Array.isArray(input)) return input; return Object.fromEntries(Object.entries(input).filter(([key]) => key !== "confirmation")) as JsonValue; }
function visibilityDecision(visibility: ToolVisibilityPolicy, definition: K13ActionDefinition, operation: K13OperationDefinition, context: RequestContext, snapshot: CapabilitySnapshot | null, updates: ProviderToolUpdateMode) { return visibility.evaluate({ tool: { tool_name: `${definition.action_id}:${operation.operation}`, required_scopes: operation.required_scopes, permission_policy: operation.permission_policy, is_public: false }, context, snapshot, provider_tool_updates: updates, catalog_contains_tool: true }); }
function decisionError(operation: K13OperationDefinition, context: RequestContext, reason: ReturnType<typeof visibilityDecision>["reason"]): Error { if (reason === "SCOPE_REQUIRED") return createConnectorError({ code: "SCOPE_REQUIRED", message: "Der OAuth-Grant enthält nicht alle erforderlichen Sponsor-, Mitglieder- oder Datei-Scopes.", request_id: context.request_id, retryable: false, required_scope: operation.required_scopes[0] }); if (["TENANT_MISMATCH", "DEPARTMENT_MISMATCH"].includes(reason)) return error(context, "TENANT_MISMATCH", "Der Vereins- oder Abteilungskontext ist nicht zulässig."); if (reason === "CONTEXT_MISSING") return error(context, "CLUB_SELECTION_REQUIRED", "Bitte wähle zuerst einen Verein aus."); return error(context, "PERMISSION_DENIED", "Die Sponsoring-Aktion ist im aktuellen Berechtigungskontext nicht erlaubt."); }
function validateRuntime(): void { for (const definition of Object.values(K13_ACTION_DEFINITIONS)) { if (!K13_ACTION_SCHEMAS[definition.action_id]) throw new Error(`${definition.action_id}: Schema fehlt.`); for (const operation of Object.values(definition.operations)) if (operation.execution_gate !== "job" && !hasK13OperationHandler(definition.action_id, operation.operation)) throw new Error(`${definition.action_id}:${operation.operation}: Handler fehlt.`); } }

export class SponsorToolSet {
  readonly #dependencies: K13ExecutionDependencies; readonly #visibility: ToolVisibilityPolicy; readonly #confirmation: NonNullable<K13ExecutionDependencies["confirmation"]>; readonly visibilityPolicy = new SponsorVisibilityPolicy();
  constructor(dependencies: K13ExecutionDependencies, visibility = new ToolVisibilityPolicy()) { validateK13Definitions(); validateRuntime(); this.#dependencies = dependencies; this.#visibility = visibility; this.#confirmation = dependencies.confirmation ?? new SponsorConfirmationPolicy(); }
  listDefinitions(): K13ActionDefinition[] { return Object.values(K13_ACTION_DEFINITIONS).map((definition) => structuredClone(definition)); }
  publicReadContracts() { return [structuredClone(PUBLIC_READ_CONTRACTS.public_sponsors)]; }
  listVisible(input: K13VisibilityRequest): K13ActionDefinition[] { const context = normalizeRequestContext(input.context); return this.listDefinitions().flatMap((definition) => { const operations = Object.fromEntries(Object.values(definition.operations).filter((operation) => { if (["write_safety", "confirmation"].includes(operation.execution_gate) && !this.#dependencies.write_safety) return false; if (operation.execution_gate === "job" && !this.#dependencies.job_starter) return false; return visibilityDecision(this.#visibility, definition, operation, context, input.capability_snapshot, input.provider_tool_updates ?? "dynamic").visible; }).map((operation) => [operation.operation, operation])); return Object.keys(operations).length ? [{ ...definition, operations }] : []; }); }
  async execute(requestInput: K13ExecutionRequest): Promise<K13ActionResult> {
    const context = normalizeRequestContext(requestInput.context); const definition = K13_ACTION_DEFINITIONS[requestInput.action_id]; if (!definition) throw error(context, "NOT_FOUND", "Die angeforderte Sponsoring-Aktion ist nicht verfügbar.");
    let input: unknown; try { input = K13_ACTION_SCHEMAS[definition.action_id].input.parse(requestInput.input); } catch (cause) { if (cause instanceof z.ZodError) throw error(context, "VALIDATION_FAILED", "Die Tool-Eingabe entspricht nicht dem freigegebenen Sponsoring-Schema."); throw cause; }
    assertJson(input, context); let operation: K13OperationDefinition; try { operation = operationFor(definition, input); } catch { throw error(context, "VALIDATION_FAILED", "Die angeforderte Teiloperation ist nicht freigegeben."); }
    if (!context.club_id) throw error(context, "CLUB_SELECTION_REQUIRED", "Bitte wähle zuerst einen Verein aus.");
    if (valuesFor(input, new Set(["club_id"])).some((id) => id !== context.club_id)) throw error(context, "TENANT_MISMATCH", "Der Tool-Aufruf gehört nicht zum ausgewählten Verein.");
    if (context.department_id && valuesFor(input, new Set(["department_id", "club_department_id"])).some((id) => id !== context.department_id)) throw error(context, "TENANT_MISMATCH", "Die Aktion überschreitet den gewählten Abteilungskontext.");
    if (operation.operation === "move_department" && context.department_id && valuesFor(input, new Set(["target_department_id"])).some((id) => id !== context.department_id)) throw error(context, "TENANT_MISMATCH", "Abteilungsverschiebungen benötigen einen clubweiten Berechtigungskontext.");
    const decision = visibilityDecision(this.#visibility, definition, operation, context, requestInput.capability_snapshot, "dynamic"); if (!decision.authorized) throw decisionError(operation, context, decision.reason); const snapshot = requestInput.capability_snapshot; if (!snapshot) throw error(context, "PERMISSION_DENIED", "Der aktuelle Berechtigungskontext fehlt.");
    const mutationRequest: K13MutationRequest = { definition, operation, input, context, capability_snapshot: snapshot }; const safeMutationRequest = { ...mutationRequest, input: withoutConfirmation(input) }; const mutation = () => executeK13Operation(definition.action_id, operation.operation, input, context, this.#dependencies.client);
    try {
      let result: JsonValue; let status: K13ActionResult["status"] = "completed";
      if (operation.execution_gate === "inline") result = await mutation();
      else if (operation.execution_gate === "job") { if (!this.#dependencies.job_starter) throw error(context, "CONFIG_INVALID", "Der sichere Sponsor-Job-Start ist nicht konfiguriert."); result = await this.#dependencies.job_starter.start(safeMutationRequest); status = "queued"; }
      else if (operation.execution_gate === "write_safety") { if (!this.#dependencies.write_safety) throw error(context, "CONFIG_INVALID", "Der Write-Safety-Flow ist nicht konfiguriert."); result = await this.#dependencies.write_safety.execute(safeMutationRequest, mutation); }
      else { if (!this.#dependencies.write_safety) throw error(context, "CONFIG_INVALID", "Der Write-Safety-Flow ist nicht konfiguriert."); const preview = await buildK13Preview(definition, operation, input, context); result = await this.#confirmation.confirmOrPreview({ mutation: mutationRequest, ...preview, confirmation: confirmationFrom(input) }, () => this.#dependencies.write_safety!.execute(safeMutationRequest, mutation)); if (result !== null && typeof result === "object" && !Array.isArray(result) && result.confirmation_required === true) status = "confirmation_required"; }
      const parsed = K13_ACTION_SCHEMAS[definition.action_id].output.safeParse(result); if (!parsed.success) throw error(context, "UPSTREAM_UNAVAILABLE", "Der Fachservice hat keine freigegebene Antwort geliefert."); assertJson(parsed.data, context); return { action_id: definition.action_id, operation: operation.operation, status, result: parsed.data };
    } catch (cause) { if (isConnectorError(cause) && cause.code === "PERMISSION_DENIED") { await this.#dependencies.on_backend_forbidden?.({ action_id: definition.action_id, operation: operation.operation, context }); throw error(context, "PERMISSION_DENIED", "Der Marketing-Service hat die Sponsoring-Aktion im aktuellen Kontext abgelehnt."); } if (isConnectorError(cause) && cause.code === "NOT_FOUND") throw error(context, "NOT_FOUND", "Die angeforderte Sponsoring-Ressource wurde nicht gefunden."); throw cause; }
  }
}
export function createK13ToolSet(dependencies: K13ExecutionDependencies): SponsorToolSet { return new SponsorToolSet(dependencies); }
