import { mcpAppsBridgeClientSource } from "../shared/client-bridge.ts";

export const CONFIRMATION_WIDGET_CLIENT = String.raw`(()=>{"use strict";
const root=document.getElementById("app");
let action=null,credential=null,busy=false;
${mcpAppsBridgeClientSource("Comvenio Aktionsbestätigung")}
const object=value=>value!==null&&typeof value==="object"&&!Array.isArray(value);
const node=(tag,value,cls)=>{const item=document.createElement(tag);item.textContent=String(value??"");if(cls)item.className=cls;return item};
const exactWidgetInput=input=>object(input)&&Object.keys(input).sort().join(",")==="idempotency_key,preview_id"&&typeof input.preview_id==="string"&&typeof input.idempotency_key==="string";
const exactCredential=input=>object(input)&&Object.keys(input).sort().join(",")==="confirmation_token,idempotency_key,preview_id"&&typeof input.preview_id==="string"&&typeof input.confirmation_token==="string"&&typeof input.idempotency_key==="string";
const valid=model=>object(model)&&model.widget==="confirmation"&&model.contract_version==="1.0.0"&&typeof model.capability_version==="string"&&object(model.club)&&object(model.data)&&object(model.data.preview)&&model.data.preview.club_id===model.club.club_id&&Array.isArray(model.actions)&&model.actions.length===1&&object(model.actions[0])&&model.actions[0].visibility==="visible"&&model.actions[0].enabled===true&&model.actions[0].tool_name==="action_confirm"&&model.actions[0].risk_class==="critical_write"&&model.actions[0].requires_confirmation===true&&exactWidgetInput(model.actions[0].input)&&model.actions[0].input.preview_id===model.data.preview.preview_id&&Date.parse(model.data.preview.expires_at)>Date.now();
const hiddenCredential=(value,depth=0)=>{if(!object(value)||depth>4)return null;const direct=object(value["comvenio/confirmation"])?value["comvenio/confirmation"]:object(value.comvenio_confirmation)?value.comvenio_confirmation:null;if(exactCredential(direct))return direct;for(const key of ["_meta","mcp_tool_result","call_tool_result","result"]){const nested=hiddenCredential(value[key],depth+1);if(nested)return nested}return null};
const resultEnvelope=params=>{if(!object(params))return null;return object(params.result)?params.result:params};
const resultModel=value=>{const result=resultEnvelope(value);if(!result)return null;return object(result.structuredContent)?result.structuredContent:object(result.structured_content)?result.structured_content:result.widget==="confirmation"?result:null};
const status=(title,message)=>{action=null;credential=null;busy=false;root.replaceChildren();const overlay=node("main","","overlay-demo"),host=node("section","","dialog-host"),panel=node("article","","confirm-sheet");panel.setAttribute("role","status");panel.append(node("h2",title),node("p",message));host.append(panel);overlay.append(host);root.append(overlay)};
const dismiss=()=>status("Aktion abgebrochen","Es wurde nichts ausgeführt.");
const call=button=>{if(busy||!action||!credential||action.enabled!==true)return;busy=true;button.disabled=true;button.textContent="Wird bestätigt …";callMcpAppsTool(action.tool_name,{preview_id:credential.preview_id,confirmation_token:credential.confirmation_token,idempotency_key:credential.idempotency_key},"confirm-"+Date.now())};
const render=(model,metadata)=>{const secret=hiddenCredential(metadata);if(!valid(model)||!secret||secret.preview_id!==model.data.preview.preview_id||secret.idempotency_key!==model.actions[0].input.idempotency_key){status("Neue Vorschau erforderlich","Die Vorschau ist abgelaufen, verändert oder nicht sicher an diese Oberfläche gebunden.");return}action=model.actions[0];credential=secret;busy=false;root.replaceChildren();const overlay=node("main","","overlay-demo"),host=node("section","","dialog-host"),panel=node("article","","confirm-sheet");panel.setAttribute("role","dialog");panel.setAttribute("aria-modal","true");panel.setAttribute("aria-labelledby","confirm-title");panel.append(node("span","Kritische Aktion","pill"));const title=node("h2",model.data.confirm_label+"?");title.id="confirm-title";panel.append(title,node("p",model.data.preview.safe_summary));const impact=node("section","","impact"),cards=[["Verein",model.club.name],["Wirkung",model.data.preview.impact.summary],["Gültig bis",new Date(model.data.preview.expires_at).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})+" Uhr"],["Ziel",model.data.preview.target.label],["Betroffen",model.data.preview.impact.affected_total],["Risiko","Kritische Aktion"]];cards.forEach(([label,value])=>{const card=node("div","");card.append(node("span",label),node("strong",value));impact.append(card)});panel.append(impact);const privacy=node("section","","permission-note");privacy.append(node("strong","Datenschutz:"),node("p","Die Vorschau enthält keine sensiblen Rohwerte. Der Einmalnachweis bleibt für das Modell verborgen."));if(Array.isArray(model.data.preview.masked_fields)&&model.data.preview.masked_fields.length){const list=node("ul","");model.data.preview.masked_fields.forEach(field=>{const item=node("li","");item.append(node("span",String(field).replaceAll(/[._-]/g," ")),node("strong","Geschützt"));list.append(item)});privacy.append(list)}panel.append(privacy);if(model.data.acknowledgement_required===true)panel.append(node("p","Mit der Bestätigung wird ausschließlich der oben dargestellte, serverseitig gespeicherte Intent ausgeführt.","acknowledgement"));host.append(panel);const bar=node("div","","actions"),cancel=node("button",model.data.cancel_label,"btn btn-secondary cancel-action"),confirm=node("button",action.label,"btn btn-primary confirm-action");cancel.type="button";confirm.type="button";cancel.addEventListener("click",dismiss);confirm.addEventListener("click",()=>call(confirm));bar.append(cancel,confirm);host.append(bar);overlay.append(host);root.append(overlay);const focusable=[cancel,confirm];confirm.focus();host.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();dismiss();return}if(event.key!=="Tab")return;const first=focusable[0],last=focusable[1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}})};
const consume=value=>{const result=resultEnvelope(value),model=resultModel(value),metadata=result??value;if(model){render(model,metadata);return true}return false};
window.addEventListener("message",event=>{if(event.source!==window.parent||!object(event.data)||event.data.jsonrpc!=="2.0")return;if(handleMcpAppsBridgeMessage(event.data))return;if(event.data.method==="ui/notifications/tool-result"){if(!consume(event.data.params)&&busy)status("Aktion verarbeitet","Comvenio hat die Bestätigung verarbeitet.")}else if(typeof event.data.id!=="undefined"&&object(event.data.result)){if(!consume(event.data.result)&&busy)status("Aktion verarbeitet","Comvenio hat die Bestätigung verarbeitet.")}});
function initialize(){status("Vorschau wird geladen","Comvenio lädt die aktuelle, serverseitig gebundene Wirkungsvorschau.");initializeMcpAppsBridge()}initialize();})();`;
