import { mcpAppsBridgeClientSource } from "../shared/client-bridge.ts";

export const EVENT_CALENDAR_WIDGET_CLIENT = String.raw`(()=>{"use strict";
const MAX_EVENTS=200,MAX_ACTIONS=50,root=document.getElementById("app");let actions=[];
${mcpAppsBridgeClientSource("Comvenio Event & Kalender")}
const text=(tag,value,cls)=>{const node=document.createElement(tag);node.textContent=String(value??"");if(cls)node.className=cls;return node};
const validObject=value=>value!==null&&typeof value==="object"&&!Array.isArray(value);
const validModel=model=>validObject(model)&&model.widget==="event_calendar"&&model.contract_version==="1.0.0"&&validObject(model.data)&&Array.isArray(model.data.events)&&model.data.events.length<=MAX_EVENTS&&Array.isArray(model.actions)&&model.actions.length<=MAX_ACTIONS&&model.actions.every(action=>validObject(action)&&action.visibility==="visible");
const format=(value,timezone,withTime=true)=>{try{return new Intl.DateTimeFormat("de-DE",withTime?{dateStyle:"medium",timeStyle:"short",timeZone:timezone}:{dateStyle:"medium",timeZone:timezone}).format(new Date(value))}catch{return "Zeit nicht verfügbar"}};
const status=(title,message,retry=false)=>{root.replaceChildren();const page=text("main","","page"),panel=text("section","","widget state-panel");panel.setAttribute("role","status");panel.append(text("h2",title),text("p",message));if(retry){const button=text("button","Erneut versuchen","btn btn-secondary");button.type="button";button.addEventListener("click",()=>initialize());panel.append(button)}page.append(panel);root.append(page)};
const callTool=(action,index)=>{if(!validObject(action)||action.enabled!==true||action.visibility!=="visible"||typeof action.tool_name!=="string"||!validObject(action.input))return;const id="tool-"+Date.now()+"-"+index;callMcpAppsTool(action.tool_name,action.input,id)};
const render=model=>{if(!validModel(model)){status("Kalender nicht verfügbar","Die Kalenderdaten konnten nicht sicher verarbeitet werden.",true);return}actions=model.actions.filter(action=>action.visibility==="visible");root.replaceChildren();const page=text("main","","page"),widget=text("section","","widget"),head=text("header","","widget-head"),heading=text("div","");heading.append(text("p","Comvenio · Kalender","eyebrow"),text("h2",model.title),text("p","Termine im gewählten Verein entdecken und verwalten."));head.append(heading);if(validObject(model.club)&&typeof model.club.name==="string")head.append(text("span",model.club.name,"context-chip"));widget.append(head);
const filter=text("div","","filter-region"),toolbar=text("div","","toolbar");toolbar.setAttribute("aria-label","Kalenderfilter");toolbar.append(text("span",model.data.view==="month"?"Monat":model.data.view==="week"?"Woche":"Agenda","field"));filter.append(toolbar);widget.append(filter);
const body=text("div","","widget-body split"),calendar=text("section","","calendar calendar-grid");calendar.setAttribute("aria-label","Kalenderübersicht");const timezone=validObject(model.club)&&typeof model.club.timezone==="string"?model.club.timezone:"Europe/Berlin";model.data.events.slice(0,31).forEach(event=>{if(!validObject(event))return;const day=text("div","","day");day.append(text("strong",format(event.start,timezone,false)),text("span",event.title));calendar.append(day)});body.append(calendar);const agenda=text("aside","","stack agenda");agenda.setAttribute("aria-label","Terminagenda");
if(model.data.events.length===0&&validObject(model.empty_state)){const empty=text("section","","state-panel empty-state");empty.append(text("h3",model.empty_state.title),text("p",model.empty_state.description));agenda.append(empty)}
model.data.events.forEach((event,index)=>{if(!validObject(event)||typeof event.title!=="string")return;const card=text("article","","event-card");if(index>=100)card.dataset.virtualized="true";card.append(text("span",model.capability_version===null?"Öffentlich":event.status==="cancelled"?"Abgesagt":"Vereinstermin","pill"),text("h3",event.title));if(typeof event.summary==="string")card.append(text("p",event.summary));const meta=text("div","","meta");meta.append(text("span",format(event.start,timezone)+" – "+format(event.end,timezone)));if(typeof event.location==="string")meta.append(text("span",event.location));card.append(meta);agenda.append(card)});body.append(agenda);widget.append(body);
if(actions.length){const bar=text("div","","actions");bar.setAttribute("aria-label","Erlaubte Eventaktionen");actions.forEach((action,index)=>{if(action.enabled!==true)return;const button=text("button",action.label,action.risk_class==="critical_write"?"btn btn-danger":"btn btn-primary");button.type="button";button.addEventListener("click",()=>callTool(action,index));bar.append(button)});if(bar.childNodes.length)widget.append(bar)}page.append(widget);root.append(page)};
const resultModel=params=>{if(!validObject(params))return null;const result=validObject(params.result)?params.result:params;return validObject(result.structuredContent)?result.structuredContent:validObject(result.structured_content)?result.structured_content:validObject(result)&&result.widget==="event_calendar"?result:null};
window.addEventListener("message",event=>{if(event.source!==window.parent||!validObject(event.data)||event.data.jsonrpc!=="2.0")return;if(handleMcpAppsBridgeMessage(event.data))return;if(event.data.method==="ui/notifications/tool-result"){const model=resultModel(event.data.params);if(model)render(model)}else if(typeof event.data.id!=="undefined"&&validObject(event.data.result)){const model=resultModel(event.data.result);if(model)render(model)}});
function initialize(){status("Kalender wird geladen","Comvenio lädt die für dich freigegebenen Termine.");initializeMcpAppsBridge()}
initialize();})();`;
